"""add specs to products

Revision ID: 591a8fca1ded
Revises: 202604010001o
Create Date: 2026-06-24 06:15:48.088851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591a8fca1ded'
down_revision = '202604010001o'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('specs', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specs')
    # ### end Alembic commands ###
